// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-Bw0bGQZdL8G5Rrt3-_9asCuTrduceo',
    appId: '1:619264119180:web:a083e528b6abac4b6106a9',
    messagingSenderId: '619264119180',
    projectId: 'web2-e85d3',
    authDomain: 'web2-e85d3.firebaseapp.com',
    storageBucket: 'web2-e85d3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQSNlhnZuT8WR6DTRx5tMb1Y27oq9Q1o',
    appId: '1:619264119180:android:37b8382df3014bb26106a9',
    messagingSenderId: '619264119180',
    projectId: 'web2-e85d3',
    storageBucket: 'web2-e85d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8eKa8Ls-wtlx6EKM2LyqJeoDnjJuvcJA',
    appId: '1:619264119180:ios:40161833abdc44d76106a9',
    messagingSenderId: '619264119180',
    projectId: 'web2-e85d3',
    storageBucket: 'web2-e85d3.appspot.com',
    iosBundleId: 'com.example.littlesteps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8eKa8Ls-wtlx6EKM2LyqJeoDnjJuvcJA',
    appId: '1:619264119180:ios:40161833abdc44d76106a9',
    messagingSenderId: '619264119180',
    projectId: 'web2-e85d3',
    storageBucket: 'web2-e85d3.appspot.com',
    iosBundleId: 'com.example.littlesteps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs-Bw0bGQZdL8G5Rrt3-_9asCuTrduceo',
    appId: '1:619264119180:web:90e6af22a6d5430d6106a9',
    messagingSenderId: '619264119180',
    projectId: 'web2-e85d3',
    authDomain: 'web2-e85d3.firebaseapp.com',
    storageBucket: 'web2-e85d3.appspot.com',
  );
}
