name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          flutter-version: '3.22.1'
          channel: stable

      - run: flutter --version
      - run: dart --version

      - run: flutter pub get
      - run: flutter test
      #- run: flutter analyze
      - run: flutter build apk --release
